---
- name: Install gnome desktop environment
  hosts: all
  become: true

  tasks:

    - name: Install apt packages
      apt:
        name:
          - gnome
          - gdm3
        state: latest
