---
- name: Install Rust
  hosts: all

  tasks:

    - name: Install Rust (rustup)
      shell: curl https://sh.rustup.rs -sSf | sh -s -- -y
      args:
        creates: /home/vagrant/.cargo/bin/cargo

    - name: Add cargo to global PATH
      become: true
      copy:
        dest: /etc/profile.d/rust.sh
        content: 'export PATH="/home/vagrant/.cargo/bin:$PATH"'

