---
- name: Install kubectl
  hosts: all
  become: true

  tasks:
    - name: Get latest kubectl version
      ansible.builtin.uri:
        url: https://dl.k8s.io/release/stable.txt
        return_content: true
      register: kubectl_version

    - name: Download kubectl binary
      ansible.builtin.get_url:
        url: "https://dl.k8s.io/release/{{ kubectl_version.content }}/bin/linux/amd64/kubectl"
        dest: /usr/local/bin/kubectl
        mode: '0755'

    - name: Add kubectl aliases
      ansible.builtin.copy:
        dest: /etc/profile.d/kubectl_aliases.sh
        mode: '0755'
        content: |
          alias k='kubectl'
          alias kgp='kubectl get pods'
          alias kgs='kubectl get svc'
          alias kga='kubectl get all'
          alias kdp='kubectl describe pod'
          source <(kubectl completion bash)
          complete -o default -F __start_kubectl k
