---
- name: Configure Kafka
  hosts: all

  vars:
    kafka_cluster_id: "{{ kafka }}/cluster.id"
    kafka_logs: "{{ kafka }}/logs"
    kafka_config: /vagrant/kafka/server.properties

  tasks:
    - name: Check if cluster ID exists
      ansible.builtin.stat:
        path: "{{ kafka_cluster_id }}"
      register: cluster_id_file

    - name: Generate Kafka cluster ID if not exist
      when: not cluster_id_file.stat.exists
      block:
        - name: Generate Kafka cluster ID
          ansible.builtin.command: "{{ kafka_bin }}/kafka-storage.sh random-uuid"
          register: kafka_uuid
          changed_when: false

        - name: Save cluster ID
          ansible.builtin.copy:
            content: "{{ kafka_uuid.stdout }}"
            dest: "{{ kafka_cluster_id }}"
            mode: "0444"

    - name: Read existing cluster ID
      ansible.builtin.command: "cat {{ kafka_cluster_id }}"
      register: kafka_uuid
      changed_when: false

    - name: Configure Kafka broker
      ansible.builtin.command: >
        {{ kafka_bin }}/kafka-storage.sh format
        --standalone
        -t {{ kafka_uuid.stdout }}
        -c {{ kafka_config }}
      args:
        creates: "{{ kafka_logs }}/meta.properties"

    - name: Create Kafka systemd service
      become: true
      ansible.builtin.template:
        src: ./systemd/kafka.service.j2
        dest: /etc/systemd/system/kafka.service
        mode: '0644'

    - name: Reload systemd
      become: true
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Enable and start Kafka
      become: true
      ansible.builtin.systemd:
        name: kafka
        enabled: true
        state: restarted

